#!/usr/bin/env python3
"""Infrahub -> collector configuration.

This is the interconnect. It is why an SNMP metric and a syslog line from the
same device both arrive labelled with the same device/site/role: both Telegraf
and Logstash read the identity table this script writes.

Reads : Infrahub (active, via SDK) + platforms.yml + telegraf/profiles/*.tmpl
Writes: /generated/
    snmp-interfaces.conf   IF-MIB for the whole fleet (one input)
    snmp-<platform>.conf   CPU + memory, one input per platform
    gnmi.conf              devices with telemetry_mode=gnmi
    devices.json           identity table for Telegraf processors.lookup
    devices.yml            the same table for the Logstash translate filter

Run with: make render   (after every `make seed` or Infrahub change)
"""
from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

import yaml
from infrahub_sdk import Config, InfrahubClientSync

INFRAHUB_URL = os.environ.get("INFRAHUB_ADDRESS", "http://infrahub-server:8000")
TOKEN = os.environ.get("INFRAHUB_API_TOKEN") or os.environ.get("INFRAHUB_INITIAL_ADMIN_TOKEN")
BRANCH = os.environ.get("INFRAHUB_BRANCH", "main")

PLATFORMS_FILE = os.environ.get("PLATFORMS_FILE", "/platforms.yml")
PROFILE_DIR = os.environ.get("PROFILE_DIR", "/profiles")
OUT_DIR = os.environ.get("RENDER_OUT_DIR", "/generated")

# Agents per [[inputs.snmp]] instance. Each instance is its own gather loop, so
# sharding keeps one unreachable device from eating the whole fleet's poll
# window, and makes a Telegraf error line say WHICH group of devices is slow.
# 150 x 30 interfaces is a comfortable walk inside a 60s interval.
SHARD_SIZE = int(os.environ.get("SNMP_SHARD_SIZE", "150"))

HEADER = (
    "# GENERATED by render-inventory.py — DO NOT EDIT.\n"
    "# Your changes are lost on the next `make render`.\n"
    "# Edit platforms.yml, the templates in observability/telegraf/profiles/,\n"
    "# or the device in Infrahub instead.\n\n"
)


def target_of(dev) -> str:
    """The address to poll. Strips any /prefix an IPHost attribute carries."""
    ip = str(getattr(dev.management_ip, "value", "") or "").strip()
    return ip.split("/")[0]


def fetch_devices(client):
    """Active, monitored devices with their site relationship resolved.

    prefetch_relationships=True is REQUIRED: without it `dev.site.peer` raises
    NodeNotFoundError, because the SDK never loaded the peer into its store.
    """
    return client.filters(
        kind="NetworkDevice",
        branch=BRANCH,
        status__value="active",
        prefetch_relationships=True,
        populate_store=True,
    )


def resource_tables(platform: str, spec: dict) -> str:
    """Build the CPU and memory tables for one platform.

    Two separate tables because Prometheus sees <measurement>_<field>: the
    measurement `cpu` with field `usage` is what produces the metric name
    `cpu_usage`, identically on every vendor despite three different MIBs.

    Memory fields vary by what the vendor actually exposes (used/free, or
    used/total, or a ready-made percentage). The memory_kind tag records which,
    and Prometheus recording rules do the conversion — see rules/recording.yml.
    """
    lines = [
        '  [[inputs.snmp.table]]',
        '    name = "cpu"',
        '    index_as_tag = true',
        '    inherit_tags = ["hostname"]',
        '',
        '    [[inputs.snmp.table.field]]',
        '      name = "usage"',
        f'      oid = "{spec["cpu"]["oid"]}"',
        '',
        '  [[inputs.snmp.table]]',
        '    name = "memory"',
        '    index_as_tag = true',
        '    inherit_tags = ["hostname"]',
    ]
    mem = spec["memory"]
    for key in ("used", "free", "total"):
        if key in mem:
            lines += [
                '',
                '    [[inputs.snmp.table.field]]',
                f'      name = "{key}"',
                f'      oid = "{mem[key]}"',
            ]
    return "\n".join(lines)


def main() -> int:
    if not TOKEN:
        print("!! INFRAHUB_API_TOKEN not set", file=sys.stderr)
        return 2

    with open(PLATFORMS_FILE) as fh:
        platforms = yaml.safe_load(fh)

    client = InfrahubClientSync(address=INFRAHUB_URL, config=Config(api_token=TOKEN))
    devices = fetch_devices(client)

    if not devices:
        print("!! no active devices in Infrahub — nothing to render.", file=sys.stderr)
        print("   Add them to source-of-truth/devices/devices.yml, then: make seed", file=sys.stderr)
        return 1

    os.makedirs(OUT_DIR, exist_ok=True)

    # Clear previous output first. Without this, shrinking the fleet (or
    # dropping a platform) leaves an orphaned shard file behind and Telegraf
    # keeps polling devices that are no longer in the source of truth.
    for stale in os.listdir(OUT_DIR):
        if stale.startswith(("snmp-", "gnmi")) and stale.endswith(".conf"):
            os.remove(os.path.join(OUT_DIR, stale))

    identity: dict[str, dict] = {}
    by_platform: dict[str, list] = defaultdict(list)
    gnmi_targets: list[str] = []
    snmp_targets: list[str] = []
    warnings: list[str] = []

    for dev in devices:
        name = dev.name.value
        platform = dev.platform.value
        target = target_of(dev)
        site = dev.site.peer.name.value if dev.site.peer else "unknown"
        role = dev.role.value
        mode = getattr(dev.telemetry_mode, "value", "snmp") or "snmp"

        if platform not in platforms:
            warnings.append(f"{name}: platform '{platform}' has no entry in platforms.yml — skipped")
            continue
        if not target:
            warnings.append(f"{name}: no management_ip — skipped")
            continue

        # The identity table is keyed by BOTH the poll target and the device
        # name, because Telegraf matches on the agent's IP while Logstash
        # matches on the hostname a syslog line carries.
        record = {"device": name, "site": site, "role": role, "platform": platform}
        identity[target] = record
        identity[name] = record

        if mode == "gnmi":
            if not platforms[platform].get("gnmi"):
                warnings.append(
                    f"{name}: telemetry_mode=gnmi but platform '{platform}' does not "
                    f"support gNMI — no metrics will be collected for this device"
                )
                continue
            port = platforms[platform].get("gnmi_port", 57400)
            gnmi_targets.append(f"{target}:{port}")
        else:
            snmp_targets.append(target)
            by_platform[platform].append(target)

    written: list[str] = []

    def write(filename: str, body: str):
        path = os.path.join(OUT_DIR, filename)
        with open(path, "w") as fh:
            fh.write(HEADER + body)
        written.append(filename)

    def agents(targets: list[str]) -> str:
        return ", ".join(f'"udp://{t}:161"' for t in sorted(targets))

    def shards(targets: list[str]) -> list[list[str]]:
        ordered = sorted(targets)
        return [ordered[i:i + SHARD_SIZE] for i in range(0, len(ordered), SHARD_SIZE)]

    # --- interfaces: IF-MIB is identical on every platform, so the fleet is
    # split by COUNT rather than by vendor. Each shard is an independent
    # gather loop.
    if snmp_targets:
        with open(os.path.join(PROFILE_DIR, "_interfaces.conf.tmpl")) as fh:
            tmpl = fh.read()
        groups = shards(snmp_targets)
        for n, group in enumerate(groups, 1):
            suffix = "" if len(groups) == 1 else f"-{n}"
            write(f"snmp-interfaces{suffix}.conf", tmpl.replace("__AGENTS__", agents(group)))

    # --- cpu + memory: one input per platform ---------------------------
    with open(os.path.join(PROFILE_DIR, "_resources.conf.tmpl")) as fh:
        res_tmpl = fh.read()

    for platform, targets in sorted(by_platform.items()):
        spec = platforms[platform]["snmp"]
        groups = shards(targets)
        for n, group in enumerate(groups, 1):
            suffix = "" if len(groups) == 1 else f"-{n}"
            body = (
                res_tmpl.replace("__AGENTS__", agents(group))
                .replace("__PLATFORM__", platform)
                .replace("__MEMORY_KIND__", spec["memory"]["kind"])
                .replace("__RESOURCE_TABLES__", resource_tables(platform, spec))
            )
            write(f"snmp-{platform}{suffix}.conf", body)

    # --- gNMI ------------------------------------------------------------
    if gnmi_targets:
        write(
            "gnmi.conf",
            "[[inputs.gnmi]]\n"
            f'  addresses = [{", ".join(chr(34) + t + chr(34) for t in sorted(gnmi_targets))}]\n'
            '  username = "${GNMI_USER}"\n'
            '  password = "${GNMI_PASSWORD}"\n'
            '  encoding = "proto"\n'
            '  redial = "10s"\n\n'
            "  [[inputs.gnmi.subscription]]\n"
            '    name = "interface"\n'
            '    origin = "openconfig"\n'
            '    path = "/interfaces/interface/state/counters"\n'
            '    subscription_mode = "sample"\n'
            '    sample_interval = "30s"\n',
        )

    # --- identity table, in both formats ---------------------------------
    write_json = os.path.join(OUT_DIR, "devices.json")
    with open(write_json, "w") as fh:
        json.dump(identity, fh, indent=2, sort_keys=True)
    written.append("devices.json")

    # Logstash's translate filter wants a flat key -> value mapping, so the
    # record is flattened into one delimited string and split in the pipeline.
    flat = {k: f"{v['device']}|{v['site']}|{v['role']}|{v['platform']}" for k, v in identity.items()}
    with open(os.path.join(OUT_DIR, "devices.yml"), "w") as fh:
        yaml.safe_dump(flat, fh, default_flow_style=False, sort_keys=True)
    written.append("devices.yml")

    # --- report -----------------------------------------------------------
    print(f"Rendered {len(devices)} device(s) from Infrahub into {OUT_DIR}:")
    for name in written:
        print(f"    {name}")
    print()
    for platform, targets in sorted(by_platform.items()):
        n = len(shards(targets))
        extra = f" across {n} shards" if n > 1 else ""
        print(f"    snmp  {platform:10} {len(targets)} device(s){extra}")
    if gnmi_targets:
        print(f"    gnmi  {'':10} {len(gnmi_targets)} device(s)")

    if warnings:
        print("\n!! warnings:", file=sys.stderr)
        for warning in warnings:
            print(f"   {warning}", file=sys.stderr)

    print("\nTelegraf picks this up within 30s (--watch-config poll).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
