#!/usr/bin/env python3
"""Infrahub -> collector configuration.

This is the interconnect. It is why an SNMP metric and a syslog line from the
same device both arrive labelled with the same device/site/role: both Telegraf
and Logstash read the identity table this script writes.

Reads : Infrahub (active, via SDK) + platforms.yml + telegraf/profiles/*.tmpl
Writes: /generated/
    snmp-interfaces.conf   IF-MIB for the whole fleet (one input)
    snmp-<platform>.conf   CPU + memory, one input per platform
    gnmi.conf              devices with telemetry_mode=gnmi
    netflow-dedicated.conf one NetFlow listener per device with flow_port set
    intent.conf + intent.influx  one intent_device series per active device —
                           what SHOULD be reporting, so dashboards and alerts can
                           name a device that is in Infrahub but silent
    services-dst.json      server ip:port/proto -> application (flow requests)
    services-src.json      the same, keyed for flow replies
    netflow-applications.conf  the lookups that apply them — only when services exist
    devices.json           identity table for Telegraf processors.lookup
    devices.yml            the same table for the Logstash translate filter

Run with: make render   (after every `make seed` or Infrahub change)
"""
from __future__ import annotations

import json
import os
import sys
from collections import defaultdict

import yaml
from infrahub_sdk import Config, InfrahubClientSync

INFRAHUB_URL = os.environ.get("INFRAHUB_ADDRESS", "http://infrahub-server:8000")
TOKEN = os.environ.get("INFRAHUB_API_TOKEN") or os.environ.get("INFRAHUB_INITIAL_ADMIN_TOKEN")
BRANCH = os.environ.get("INFRAHUB_BRANCH", "main")

PLATFORMS_FILE = os.environ.get("PLATFORMS_FILE", "/platforms.yml")
PROFILE_DIR = os.environ.get("PROFILE_DIR", "/profiles")
OUT_DIR = os.environ.get("RENDER_OUT_DIR", "/generated")

# Agents per [[inputs.snmp]] instance. Each instance is its own gather loop, so
# sharding keeps one unreachable device from eating the whole fleet's poll
# window, and makes a Telegraf error line say WHICH group of devices is slow.
# 150 x 30 interfaces is a comfortable walk inside a 60s interval.
SHARD_SIZE = int(os.environ.get("SNMP_SHARD_SIZE", "150"))

# SNMPv3 security, per level. Telegraf takes sec_level once per [[inputs.snmp]],
# so each level gets its own inputs — a device polled at the wrong level is
# silently dropped by the agent and shows only as a timeout. The file suffix
# keeps authPriv (the default, and nearly every device) on the original names.
SECURITY = {
    "auth_priv": ("", [
        'sec_level = "authPriv"',
        'auth_protocol = "SHA"',
        'auth_password = "${SNMPV3_AUTH}"',
        'priv_protocol = "AES"',
        'priv_password = "${SNMPV3_PRIV}"',
    ]),
    # For images with no privacy support at all (Cisco L2 IOL rejects `priv`).
    # Never a fleet-wide fallback: it sends every poll unencrypted.
    "auth_no_priv": ("-authnopriv", [
        'sec_level = "authNoPriv"',
        'auth_protocol = "SHA"',
        'auth_password = "${SNMPV3_AUTH}"',
    ]),
}
DEFAULT_SECURITY = "auth_priv"

# Dedicated NetFlow listeners. Flow records normally resolve to a device by
# their source address. Behind NAT (a lab on a laptop, a remote site through a
# firewall) every exporter arrives from the same address, so a device with
# flow_port set gets its own listener, tagged with its name. The range is the
# one compose publishes; render warns about a port outside it rather than
# writing a listener no packet can reach.
FLOW_FIRST = os.environ.get("FLOW_DEDICATED_FIRST", "")
FLOW_LAST = os.environ.get("FLOW_DEDICATED_LAST", "")

# Flow -> application. Runs between conf.d/netflow.conf's converter (order 3,
# which makes protocol a tag) and its override (order 7, which drops the
# addresses). A request's server is its destination, a reply's its source;
# the reply table's tags are named reply_* so the request's labels win when a
# flow matches both, and anything unmatched becomes application="other".
GEN = "/etc/telegraf/telegraf.d/generated"
APPLICATION_PROCESSORS = f'''[[processors.lookup]]
  order = 4
  namepass = ["netflow"]
  files = ["{GEN}/services-dst.json"]
  format = "json"
  key = '{{{{.Field "dst"}}}}:{{{{.Field "dst_port"}}}}/{{{{.Tag "protocol"}}}}'

[[processors.lookup]]
  order = 5
  namepass = ["netflow"]
  files = ["{GEN}/services-src.json"]
  format = "json"
  key = '{{{{.Field "src"}}}}:{{{{.Field "src_port"}}}}/{{{{.Tag "protocol"}}}}'

[[processors.starlark]]
  order = 6
  namepass = ["netflow"]
  source = \'\'\'
def apply(metric):
    t = metric.tags
    t["application"] = t.get("application") or t.get("reply_application") or "other"
    t["criticality"] = t.get("criticality") or t.get("reply_criticality") or "none"
    t.pop("reply_application", None)
    t.pop("reply_criticality", None)
    return metric
\'\'\'
'''

HEADER = (
    "# GENERATED by render-inventory.py — DO NOT EDIT.\n"
    "# Your changes are lost on the next `make render`.\n"
    "# Edit platforms.yml, the templates in observability/telegraf/profiles/,\n"
    "# or the device in Infrahub instead.\n\n"
)


def _readable(path: str) -> None:
    """World-readable, explicitly.

    This runs as root inside infrahub-server, but Logstash reads the identity
    table as uid 1000. If a restrictive umask left the file 0600, Logstash's
    translate filter would fail to load it and every log line would arrive
    labelled `unknown` — with nothing reporting why.
    """
    os.chmod(path, 0o644)


def ip_of(dev) -> str:
    """management_ip without the /prefix an IPHost attribute may carry."""
    ip = str(getattr(getattr(dev, "management_ip", None), "value", "") or "").strip()
    return ip.split("/")[0]


def security_of(dev) -> str:
    """The device's SNMPv3 level; the schema default when unset."""
    return getattr(getattr(dev, "snmp_security", None), "value", None) or DEFAULT_SECURITY


def target_of(dev) -> str:
    """The address to poll: management_host when set, else management_ip."""
    host = str(getattr(getattr(dev, "management_host", None), "value", "") or "").strip()
    return host or ip_of(dev)


def flow_port_of(dev) -> int | None:
    """The device's dedicated NetFlow port, or None when it shares the default one."""
    value = getattr(getattr(dev, "flow_port", None), "value", None)
    return int(value) if value not in (None, "") else None


def fetch_services(client) -> list:
    """Services with their host and application resolved. Optional in the
    schema: a deployment that models none — or an Infrahub without the kind —
    gets empty tables, and every flow stays application="other"."""
    try:
        return client.filters(kind="NetworkService", branch=BRANCH,
                              prefetch_relationships=True, populate_store=True)
    except Exception as exc:  # SchemaNotFoundError, or an older schema
        print(f"   (no services: {exc})", file=sys.stderr)
        return []


def service_tables(services) -> tuple[dict, dict, list[str]]:
    """ip:port/proto -> {application, criticality}, once per flow direction.

    A request's server is its destination; a reply's server is its source.
    The reply table names its tags reply_* so a server-to-server flow that
    matches both keeps the request's labels (netflow.conf merges them).
    """
    dst, src, warnings = {}, {}, []
    for svc in services:
        name = svc.name.value
        host = svc.host.peer if svc.host else None
        app = svc.application.peer if svc.application else None
        if host is None or app is None:
            warnings.append(f"service {name}: host or application missing — not labelled")
            continue
        if (getattr(host.status, "value", "active") or "active") != "active":
            continue
        address = str(getattr(host.address, "value", "") or "").split("/")[0]
        if not address:
            warnings.append(f"service {name}: host {host.name.value} has no address — not labelled")
            continue
        key = f"{address}:{svc.port.value}/{svc.protocol.value or 'tcp'}"
        criticality = getattr(app.criticality, "value", None) or "medium"
        dst[key] = {"application": app.name.value, "criticality": criticality}
        src[key] = {"reply_application": app.name.value, "reply_criticality": criticality}
    return dst, src, warnings


def fetch_devices(client):
    """Active, monitored devices with their site relationship resolved.

    prefetch_relationships=True is REQUIRED: without it `dev.site.peer` raises
    NodeNotFoundError, because the SDK never loaded the peer into its store.
    """
    return client.filters(
        kind="NetworkDevice",
        branch=BRANCH,
        status__value="active",
        prefetch_relationships=True,
        populate_store=True,
    )


def resource_tables(platform: str, spec: dict) -> str:
    """Build the CPU and memory tables for one platform.

    Two separate tables because Prometheus sees <measurement>_<field>: the
    measurement `cpu` with field `usage` is what produces the metric name
    `cpu_usage`, identically on every vendor despite three different MIBs.

    Memory fields vary by what the vendor actually exposes (used/free, or
    used/total, or a ready-made percentage). The memory_kind tag records which,
    and Prometheus recording rules do the conversion — see rules/recording.yml.
    """
    lines = [
        '  [[inputs.snmp.table]]',
        '    name = "cpu"',
        '    index_as_tag = true',
        '    inherit_tags = ["hostname"]',
        '',
        '    [[inputs.snmp.table.field]]',
        '      name = "usage"',
        f'      oid = "{spec["cpu"]["oid"]}"',
        '',
        '  [[inputs.snmp.table]]',
        '    name = "memory"',
        '    index_as_tag = true',
        '    inherit_tags = ["hostname"]',
    ]
    mem = spec["memory"]
    for key in ("used", "free", "total"):
        if key in mem:
            lines += [
                '',
                '    [[inputs.snmp.table.field]]',
                f'      name = "{key}"',
                f'      oid = "{mem[key]}"',
            ]
    if spec.get("bgp"):
        # BGP4-MIB bgpPeerTable — standard, so one definition serves every
        # platform that sets `bgp: true`. One series per peer: bounded.
        # local_addr (the session's own address) places the session on an
        # interface — the network map draws tunnel links from it.
        # state 6 = established; admin_status 2 = start (configured up).
        lines += ['', '  [[inputs.snmp.table]]', '    name = "bgp_peer"', '    inherit_tags = ["hostname"]']
        for name, oid, tag in (("peer", "1.3.6.1.2.1.15.3.1.7", True), ("state", "1.3.6.1.2.1.15.3.1.2", False),
                               ("admin_status", "1.3.6.1.2.1.15.3.1.3", False), ("remote_as", "1.3.6.1.2.1.15.3.1.9", False),
                               ("established_seconds", "1.3.6.1.2.1.15.3.1.16", False),
                               ("local_addr", "1.3.6.1.2.1.15.3.1.5", True)):
            lines += ['', '    [[inputs.snmp.table.field]]', f'      name = "{name}"', f'      oid = "{oid}"']
            if tag:
                lines.append('      is_tag = true')
    if spec.get("ipsla"):
        # CISCO-RTTMON-MIB: the latest result of every IP SLA operation the
        # device runs. index = operation id (always unique); tag = the probe's
        # name from `tag` in its config — label probes by it in dashboards.
        # rtt_type 1 = icmp-echo, 6 = tcp-connect; sense 1 = ok.
        lines += ['', '  [[inputs.snmp.table]]', '    name = "ipsla"', '    index_as_tag = true', '    inherit_tags = ["hostname"]']
        for name, oid, tag in (("probe", "1.3.6.1.4.1.9.9.42.1.2.1.1.3", True),
                               ("rtt_type", "1.3.6.1.4.1.9.9.42.1.2.1.1.4", True),
                               ("rtt_ms", "1.3.6.1.4.1.9.9.42.1.2.10.1.1", False),
                               ("sense", "1.3.6.1.4.1.9.9.42.1.2.10.1.2", False)):
            lines += ['', '    [[inputs.snmp.table.field]]', f'      name = "{name}"', f'      oid = "{oid}"']
            if tag:
                lines.append('      is_tag = true')
    if spec.get("neighbors"):
        if spec["neighbors"] != "lldp":
            raise ValueError(f"{platform}: snmp.neighbors must be 'lldp' (got {spec['neighbors']!r})")
        # LLDP-MIB (standard): who is on the other end of each physical link.
        # lldpRemTable index = <timeMark>.<localPortNum>.<remIndex>; the local
        # port's name comes from lldpLocPortTable (its id is the ifName where
        # lldpLocPortIdSubtype is 5, interfaceName). neighbor_name is the
        # neighbour's sysName, matched to the `hostname` label of the device
        # that reports it. `seen` (lldpRemChassisIdSubtype) is only there
        # because a series needs a numeric field: its existence is the link.
        lines += ['', '  [[inputs.snmp.table]]', '    name = "neighbor"', '    index_as_tag = true',
                  '    inherit_tags = ["hostname"]']
        for name, oid, tag in (("neighbor_name", "1.0.8802.1.1.2.1.4.1.1.9", True),
                               ("neighbor_port", "1.0.8802.1.1.2.1.4.1.1.7", True),
                               ("seen", "1.0.8802.1.1.2.1.4.1.1.4", False)):
            lines += ['', '    [[inputs.snmp.table.field]]', f'      name = "{name}"', f'      oid = "{oid}"']
            if tag:
                lines.append('      is_tag = true')
        lines += ['', '  [[inputs.snmp.table]]', '    name = "lldp_port"', '    index_as_tag = true',
                  '    inherit_tags = ["hostname"]',
                  '', '    [[inputs.snmp.table.field]]', '      name = "ifName"',
                  '      oid = "1.0.8802.1.1.2.1.3.7.1.3"', '      is_tag = true',
                  '', '    [[inputs.snmp.table.field]]', '      name = "id_subtype"',
                  '      oid = "1.0.8802.1.1.2.1.3.7.1.2"']
        # Tunnels carry no LLDP, so the map takes overlay links from routing:
        # each BGP session's local address (bgp_peer local_addr) and the peer
        # address resolve to interfaces through ipAddrTable (IP -> ifIndex)
        # and ifIndex -> ifName.
        lines += ['', '  [[inputs.snmp.table]]', '    name = "ip_address"', '    index_as_tag = true',
                  '    inherit_tags = ["hostname"]',
                  '', '    [[inputs.snmp.table.field]]', '      name = "ifindex"',
                  '      oid = "1.3.6.1.2.1.4.20.1.2"', '      is_tag = true',
                  '', '    [[inputs.snmp.table.field]]', '      name = "seen"',
                  '      oid = "1.3.6.1.2.1.4.20.1.4"',
                  '', '  [[inputs.snmp.table]]', '    name = "if_index"', '    index_as_tag = true',
                  '    inherit_tags = ["hostname"]',
                  '', '    [[inputs.snmp.table.field]]', '      name = "ifName"',
                  '      oid = "1.3.6.1.2.1.31.1.1.1.1"', '      is_tag = true',
                  '', '    [[inputs.snmp.table.field]]', '      name = "value"',
                  '      oid = "1.3.6.1.2.1.2.2.1.1"']
    return "\n".join(lines)


def main() -> int:
    if not TOKEN:
        print("!! INFRAHUB_API_TOKEN not set", file=sys.stderr)
        return 2

    with open(PLATFORMS_FILE) as fh:
        platforms = yaml.safe_load(fh)

    client = InfrahubClientSync(address=INFRAHUB_URL, config=Config(api_token=TOKEN))
    devices = fetch_devices(client)

    if not devices:
        print("!! no active devices in Infrahub — nothing to render.", file=sys.stderr)
        print("   Add them in the Infrahub UI, or in source-of-truth/devices/*.yml then: make seed",
              file=sys.stderr)
        print("   (start from source-of-truth/devices/examples/)", file=sys.stderr)
        return 1

    os.makedirs(OUT_DIR, exist_ok=True)

    # Clear previous output first. Without this, shrinking the fleet (or
    # dropping a platform) leaves an orphaned shard file behind and Telegraf
    # keeps polling devices that are no longer in the source of truth.
    for stale in os.listdir(OUT_DIR):
        if stale.startswith(("snmp-", "gnmi", "netflow-", "intent")) and stale.endswith((".conf", ".influx")):
            os.remove(os.path.join(OUT_DIR, stale))

    identity: dict[str, dict] = {}
    # Both keyed by SNMP security level first: one level per Telegraf input.
    by_platform: dict[tuple[str, str], list] = defaultdict(list)
    snmp_targets: dict[str, list] = defaultdict(list)
    gnmi_targets: list[str] = []
    intended: list[dict] = []
    flow_ports: dict[int, str] = {}
    warnings: list[str] = []

    for dev in devices:
        name = dev.name.value
        platform = dev.platform.value
        target = target_of(dev)
        site = dev.site.peer.name.value if dev.site.peer else "unknown"
        role = dev.role.value
        mode = getattr(dev.telemetry_mode, "value", "snmp") or "snmp"

        if platform not in platforms:
            warnings.append(f"{name}: platform '{platform}' has no entry in platforms.yml — skipped")
            continue
        if not target:
            warnings.append(f"{name}: no management_ip or management_host — skipped")
            continue

        # The identity table is keyed by the poll target AND the device name,
        # because Telegraf's SNMP metrics match on the agent address while
        # Logstash matches on the hostname a syslog line carries. When the
        # target is a DNS name, the IP is a key too: flow records match on
        # the exporter's source address, which is never a name.
        record = {"device": name, "site": site, "role": role, "platform": platform}
        identity[target] = record
        identity[name] = record
        if ip_of(dev):
            identity[ip_of(dev)] = record
        intended.append({**record, "telemetry": mode})

        # Before the telemetry branch: flow is independent of SNMP vs gNMI.
        port = flow_port_of(dev)
        if port is not None:
            if not getattr(getattr(dev, "flow_enabled", None), "value", False):
                warnings.append(f"{name}: flow_port {port} set but flow_enabled is false — listener not rendered")
            elif port in flow_ports:
                warnings.append(f"{name}: flow_port {port} already used by {flow_ports[port]} — listener not rendered")
            elif FLOW_FIRST and FLOW_LAST and not int(FLOW_FIRST) <= port <= int(FLOW_LAST):
                warnings.append(
                    f"{name}: flow_port {port} is outside the published range "
                    f"{FLOW_FIRST}-{FLOW_LAST} — no packet could reach it; listener not rendered"
                )
            else:
                flow_ports[port] = name

        if mode == "gnmi":
            if not platforms[platform].get("gnmi"):
                warnings.append(
                    f"{name}: telemetry_mode=gnmi but platform '{platform}' does not "
                    f"support gNMI — no metrics will be collected for this device"
                )
                continue
            port = platforms[platform].get("gnmi_port", 57400)
            gnmi_targets.append(f"{target}:{port}")
        else:
            level = security_of(dev)
            if level not in SECURITY:
                warnings.append(f"{name}: snmp_security '{level}' is not known to the renderer — skipped")
                continue
            snmp_targets[level].append(target)
            by_platform[(level, platform)].append(target)

    written: list[str] = []

    def write(filename: str, body: str):
        path = os.path.join(OUT_DIR, filename)
        with open(path, "w") as fh:
            fh.write(HEADER + body)
        _readable(path)
        written.append(filename)

    def agents(targets: list[str]) -> str:
        return ", ".join(f'"udp://{t}:161"' for t in sorted(targets))

    def shards(targets: list[str]) -> list[list[str]]:
        ordered = sorted(targets)
        return [ordered[i:i + SHARD_SIZE] for i in range(0, len(ordered), SHARD_SIZE)]

    def security(level: str) -> str:
        return "\n".join(f"  {line}" for line in SECURITY[level][1])

    # --- interfaces: IF-MIB is identical on every platform, so the fleet is
    # split by COUNT rather than by vendor — and by security level, since
    # each Telegraf input has one. Each shard is an independent gather loop.
    with open(os.path.join(PROFILE_DIR, "_interfaces.conf.tmpl")) as fh:
        tmpl = fh.read()
    for level, targets in sorted(snmp_targets.items()):
        groups = shards(targets)
        for n, group in enumerate(groups, 1):
            suffix = SECURITY[level][0] + ("" if len(groups) == 1 else f"-{n}")
            body = tmpl.replace("__AGENTS__", agents(group)).replace("__SECURITY__", security(level))
            write(f"snmp-interfaces{suffix}.conf", body)

    # --- cpu + memory: one input per platform ---------------------------
    with open(os.path.join(PROFILE_DIR, "_resources.conf.tmpl")) as fh:
        res_tmpl = fh.read()

    for (level, platform), targets in sorted(by_platform.items()):
        spec = platforms[platform]["snmp"]
        groups = shards(targets)
        for n, group in enumerate(groups, 1):
            suffix = SECURITY[level][0] + ("" if len(groups) == 1 else f"-{n}")
            body = (
                res_tmpl.replace("__AGENTS__", agents(group))
                .replace("__SECURITY__", security(level))
                .replace("__PLATFORM__", platform)
                .replace("__MEMORY_KIND__", spec["memory"]["kind"])
                .replace("__RESOURCE_TABLES__", resource_tables(platform, spec))
            )
            write(f"snmp-{platform}{suffix}.conf", body)

    # --- gNMI ------------------------------------------------------------
    if gnmi_targets:
        write(
            "gnmi.conf",
            "[[inputs.gnmi]]\n"
            f'  addresses = [{", ".join(chr(34) + t + chr(34) for t in sorted(gnmi_targets))}]\n'
            '  username = "${GNMI_USER}"\n'
            '  password = "${GNMI_PASSWORD}"\n'
            '  encoding = "proto"\n'
            '  redial = "10s"\n\n'
            "  [[inputs.gnmi.subscription]]\n"
            '    name = "interface"\n'
            '    origin = "openconfig"\n'
            '    path = "/interfaces/interface/state/counters"\n'
            '    subscription_mode = "sample"\n'
            '    sample_interval = "30s"\n',
        )

    # --- dedicated NetFlow listeners -------------------------------------
    # The flow_exporter tag is what processors.lookup keys on ahead of the
    # source address (conf.d/outputs.conf), so these records get the same
    # device/site/role labels as everything else.
    if flow_ports:
        blocks = []
        for port, name in sorted(flow_ports.items()):
            blocks.append(
                "[[inputs.netflow]]\n"
                f'  service_address = "udp://:{port}"\n'
                '  protocol = "netflow v9"\n'
                '  read_buffer_size = "8MiB"\n'
                "  [inputs.netflow.tags]\n"
                f'    flow_exporter = "{name}"\n'
            )
        write("netflow-dedicated.conf", "\n".join(blocks))

    # --- application tables for flow labelling ----------------------------
    # Tables first, then the processors that read them — and the processors
    # only when there is something to match. processors.lookup refuses to
    # start on a missing file, so the static conf.d never references these.
    services_dst, services_src, svc_warnings = service_tables(fetch_services(client))
    warnings.extend(svc_warnings)
    for filename, table in (("services-dst.json", services_dst), ("services-src.json", services_src)):
        path = os.path.join(OUT_DIR, filename)
        with open(path, "w") as fh:
            json.dump(table, fh, indent=2, sort_keys=True)
        _readable(path)
        written.append(filename)
    if services_dst:
        write("netflow-applications.conf", APPLICATION_PROCESSORS)

    # --- intent: what SHOULD be reporting ---------------------------------
    # The data file and the input that reads it are written together, so
    # conf.d never names a file that make render has not created yet.
    if intended:
        def esc(v: str) -> str:   # influx line protocol tag-value escaping
            return str(v).replace("\\", "\\\\").replace(",", "\\,").replace("=", "\\=").replace(" ", "\\ ")
        path = os.path.join(OUT_DIR, "intent.influx")
        with open(path, "w") as fh:
            # rank: the device's position in name order. PromQL cannot compare
            # strings, and the link rules need it to keep each link once.
            for rank, rec in enumerate(sorted(intended, key=lambda r: r["device"])):
                tags = ",".join(f"{k}={esc(rec[k])}" for k in ("device", "site", "role", "platform", "telemetry"))
                fh.write(f"intent_device,{tags} present=1i,rank={rank}i\n")
        _readable(path)
        written.append("intent.influx")
        write("intent.conf",
              "[[inputs.file]]\n"
              f'  files = ["/etc/telegraf/telegraf.d/generated/intent.influx"]\n'
              '  data_format = "influx"\n'
              # Well inside prometheus_client's 60 s expiration: at 60 s the
              # series raced its own expiry and flickered out of Prometheus.
              '  interval = "30s"\n')

    # --- identity table, in both formats ---------------------------------
    write_json = os.path.join(OUT_DIR, "devices.json")
    with open(write_json, "w") as fh:
        json.dump(identity, fh, indent=2, sort_keys=True)
    _readable(write_json)
    written.append("devices.json")

    # Logstash's translate filter wants a flat key -> value mapping, so the
    # record is flattened into one delimited string and split in the pipeline.
    flat = {k: f"{v['device']}|{v['site']}|{v['role']}|{v['platform']}" for k, v in identity.items()}
    with open(os.path.join(OUT_DIR, "devices.yml"), "w") as fh:
        yaml.safe_dump(flat, fh, default_flow_style=False, sort_keys=True)
    _readable(os.path.join(OUT_DIR, "devices.yml"))
    written.append("devices.yml")

    # --- report -----------------------------------------------------------
    print(f"Rendered {len(devices)} device(s) from Infrahub into {OUT_DIR}:")
    for name in written:
        print(f"    {name}")
    print()
    for (level, platform), targets in sorted(by_platform.items()):
        n = len(shards(targets))
        extra = f" across {n} shards" if n > 1 else ""
        print(f"    snmp  {platform:10} {level:13} {len(targets)} device(s){extra}")
    if gnmi_targets:
        print(f"    gnmi  {'':10} {len(gnmi_targets)} device(s)")
    if flow_ports:
        print(f"    flow  {'dedicated':10} {len(flow_ports)} listener(s)")
    if services_dst:
        apps = len({v["application"] for v in services_dst.values()})
        print(f"    flow  {'apps':10} {len(services_dst)} service endpoint(s), {apps} application(s)")

    if warnings:
        print("\n!! warnings:", file=sys.stderr)
        for warning in warnings:
            print(f"   {warning}", file=sys.stderr)

    print("\nTelegraf picks this up within 30s (--watch-config poll).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
